// Job options with IDs
export const jobOptions = [
    { id: 1, name: '게임개발자' },
    { id: 2, name: '게임 프로그래머' },
    { id: 3, name: '게임 그래픽 디자이너' },
    { id: 4, name: 'VR/AR 콘텐츠 개발자' },
    { id: 5, name: '모바일 게임 개발자' },
    { id: 6, name: '“소프트웨어 엔지니어' },
    { id: 7, name: '백엔드/프론트엔드 개발자' },
    { id: 8, name: '데이터베이스 관리자(DBA)' },
    { id: 9, name: 'UI/UX 디자이너' },
    { id: 10, name: '클라우드 엔지니어' },
    { id: 11, name: '정보보안 전문가(CISO)' },
    { id: 12, name: '네트워크 보안 엔지니어' },
    { id: 13, name: '시스템 보안 관리자' },
    { id: 14, name: '악성코드 분석가' },
    { id: 15, name: '보안 컨설턴트' },
    { id: 16, name: '디지털 포렌식 전문가' },
    { id: 17, name: '침투 테스트 전문가 (펜테스터)' },
    { id: 18, name: '보안 솔루션 개발자' },
    { id: 19, name: '개인정보 보호 관리자' },
    { id: 20, name: '클라우드 보안 전문가' },
    { id: 21, name: '머신러닝 엔지니어' },
    { id: 22, name: '데이터 사이언티스트' },
    { id: 23, name: 'AI 연구원' },
    { id: 24, name: '컴퓨터 비전 엔지니어' },
    { id: 25, name: '자연어 처리(NLP) 전문가' },
    { id: 26, name: '로보틱스 소프트웨어 엔지니어' },
    { id: 27, name: '음성 인식 개발자' },
    { id: 28, name: 'AI 윤리 컨설턴트' },
    { id: 29, name: '추천 시스템 개발자' },
    { id: 30, name: '자율주행차 소프트웨어 엔지니어' },
    
  ];